workflows:
  ios-workflow:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Update these with your actual values
        BUNDLE_ID: "com.holycross.schoolapp"
        APP_NAME: "Holy Cross School"
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Flutter analyze
        script: |
          flutter analyze || true
      
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.school.holycrossangloindian.holyCrossApp" --type IOS_APP_DEVELOPMENT --create
          keychain add-certificates
      
      - name: Flutter build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      
      # Uncomment to publish to App Store Connect
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      #   submit_to_testflight: true

  android-workflow:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build APK
        script: |
          flutter build apk --release
      
      - name: Build App Bundle
        script: |
          flutter build appbundle --release
    
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
